version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: testDB
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  app:
    image: pkiop_blog
    command: deno run --allow-net --allow-env --allow-read ./server/src/app.ts
    links:
      - 'mysql:database'
    ports:
      - '8080:8080'
